name: "perf-test-service"
version: "1.0.0"

server:
  http:
    host: "127.0.0.1"
    port: 8081
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  tls:
    enabled: false
    cert_file: "localhost+4.pem"
    key_file: "localhost+4-key.pem"

logger:
  level: "info"

cache:
  enabled: false

actions:
  enabled: false
  webhooks:
    enabled: false
  events:
    order.created:

cron:
  enabled: false

middlewares:
  enabled: false
  recovery:
    enabled: false
  logging:
    enabled: false
  rate_limit:
    enabled: false
    params:
      requests_per_minute: 100000000
  body_limit:
    enabled: false
  cors:
    enabled: false
  auth:
    enabled: false
    params:
      token: 12345
  cache:
    enabled: false
  compression:
    enabled: false
    params:
      algorithm: "br"

docs:
  enabled: false

metrics:
  enabled: false

health:
  enabled: false

profiler:
  enabled: false
