name: "test"
version: "1.0.0"

server:
  http:
    port: 8080
  tls:
    enabled: false
    auto_cert: false
    cert_file: "localhost+4.pem"
    key_file: "localhost+4-key.pem"

cron:
  enabled: false

docs:
  enabled: false

health:
  enabled: false

metrics:
  enabled: false

actions:
  webhooks:
    enabled: false
  events:
    user.created:
      id: "string"
      value: "int64"
      created_at: "time.Time"

middlewares:
  enabled: false
  logging:
    enabled: false
    params:
      log_headers: true
      log_body: true
  auth:
    enabled: false
    weight: 70
    params:
      provider: basic

auth_providers:
  token:
    params:
      token: "your-secret-token"
  basic:
    params:
      username: "name"
      password: "pass1"

logger:
  output: "console"
  level: "debug"

profiler:
  enabled: true

blabla: 1