common:
  socket:
    port: 8002
  http:
    enabled: true
    port: 8080
  ws:
    enabled: true
    port: 8081
  cors: ["*"]
  methods: ["POST","GET","OPTIONS","DELETE"]
  headers: ["Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization"]



test: " TEST"
